word_lenght = 5

with open("bee_movie_script.txt", "r") as f:
    text = f.read()

words = set(word.upper() for word in text.split() if len(word)==word_lenght and word.isalpha())

# Open in append mode so we don’t overwrite
with open("word_list.txt", "w", encoding="utf-8") as f:
    f.write("#Fun fact! This list was generated by nothing other than the Bee movie script. Below are all the 5 letter words in the bee movie. Enjoy!\n")
    for word in words:
        f.write(word + "\n")